### PR TITLE
Feature/request body matching

### LINKED ISSUE #21: Feature: response based on POST params
While in GET method we can use regexp for matching url parameters in POST requests is no option of getting different mock response based on the POST request parameters. As a developer and tester i would like to configure mock response based on the POST parameters so i can test interaction with the application and rest api calls.

### PR DESCRIPTION
**Pull request by ainsleybc**
A **non-breaking** change to allow mocks to be matched on the request body (resolves #21).

If the mock is configured to match on the request body, this will take precedence over other mocks where the body property is not defined.

Notes:
- added optional property to mock interface (takes a regex/string - the same as the expression)
- updated the getMatchingMock function to match the body payload if defined
- added scenarios to protractor & interface tests
- updated README
- all tests passing
- linter passing

let me know if I should do anything else!

### CODE REVIEW

**Comment by lalmanzar** [comment]
Hopefully this get incorporated soon. It's a must have feature.

**Comment by wswebcreation** [comment]
Hi @ainsleybc 

Thanks for this PR, looks nice! @mdasberg is currently busy with a refactor of this module. I don't  know when this will be merged due to his time.

**Comment by mdasberg** [comment]
@ainsleybc thanks for the pr. This functionality will be added to the new version too.

**Comment by DHFW** [comment]
Hi @mdasberg, can you please release a new version soon? It is working for me, using a forked version. And, the good thing with this you can support REST *and* GraphQL with this solution (because GraphQL is using the body, not the URL). That is a big selling point for your fantastic module!

**Comment by DHFW** [comment]
@mdasberg Do you have an estimate on when you can release the new version? We have to use a workaround in our team to use the ng-api mock server now...

**Comment by mdasberg** [comment]
@DHFW I have just released v1.4.7.

**Comment by DHFW** [comment]
@mdasberg Thank you! Without any rewrites in our code we have it working now!

**Pull request merged**
